#pragma once

struct INPUT_LAYOUT_TYPE { enum { VERTEX, COLOREDVERTEX, COUNT }; };
struct VIEW_PORT_TYPE { enum { DEFAULT, COUNT }; };
struct TIME_TYPE { enum { DEFAULT, FPS, COUNT }; };

typedef enum class PIXEL_SHADER_TYPE
{
	DEFAULT,
	DEBUG,
	DEBUGMODEL,
	COUNT
} PS_TYPE;

typedef enum class VERTEX_SHADER_TYPE
{
	DEFAULT,
	DEBUG,
	DEBUGMODEL,
	COUNT
} VS_TYPE;

typedef enum class GEOMETRY_SHADER_TYPE
{
	COUNT
} GS_TYPE;

typedef enum class DOMAIN_SHADER_TYPE
{
	COUNT
} DS_TYPE;

typedef enum class HULL_SHADER_TYPE
{
	COUNT
} HS_TYPE;

enum FRUSTUM_CORNERS
{
	NEAR_TOP_LEFT, NEAR_TOP_RIGHT, 
	NEAR_BOTTOM_LEFT, NEAR_BOTTOM_RIGHT,
	FAR_TOP_LEFT, FAR_TOP_RIGHT, 
	FAR_BOTTOM_LEFT, FAR_BOTTOM_RIGHT,
	TOTAL_FRUSTUM_CORNER_COUNT
};

enum FRUSTUM_PLANES
{
	LEFT_PLANE, RIGHT_PLANE, 
	TOP_PLANE, BOTTOM_PLANE,
	NEAR_PLANE, FAR_PLANE,
	TOTAL_FRUSTUM_PLANE_COUNT
};

